services: 
  factorio: 
    image: 'factoriotools/factorio:stable'
    ports: 
      - "34197:34197/udp" #game
      - "27015:27015/tcp" #?
    restart: unless-stopped 
    environment: 
      PUID: 845
      PGID: 845
      DLC_SPACE_AGE: true # space age isn't mandatory, but it is preferred. you can run 2.0 plain though.
      LOAD_LATEST_SAVE: true 
    stop_grace_period: 2m 
    volumes: 
      - './storage:/factorio' #game operates out of the factorio directory in the container entirely, just map the entire thing. 
